//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmandoShop.ProvidersClient.Model.Services {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/ArmandoShop.Model")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ArmandoShop.ProvidersClient.Model.Services.Category categoryField;
        
        private string descriptionField;
        
        private long idField;
        
        private string nameField;
        
        private decimal priceField;
        
        private int stockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArmandoShop.ProvidersClient.Model.Services.Category category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/ArmandoShop.Model")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string descriptionField;
        
        private long idField;
        
        private string nameField;
        
        private System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Product> productsField;
        
        private System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Provider> providersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Product> products {
            get {
                return this.productsField;
            }
            set {
                if ((object.ReferenceEquals(this.productsField, value) != true)) {
                    this.productsField = value;
                    this.RaisePropertyChanged("products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Provider> providers {
            get {
                return this.providersField;
            }
            set {
                if ((object.ReferenceEquals(this.providersField, value) != true)) {
                    this.providersField = value;
                    this.RaisePropertyChanged("providers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Provider", Namespace="http://schemas.datacontract.org/2004/07/ArmandoShop.Model")]
    [System.SerializableAttribute()]
    public partial class Provider : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string addressField;
        
        private System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Category> categoriesField;
        
        private long idField;
        
        private string mailField;
        
        private string nameField;
        
        private string phoneField;
        
        private string surnameField;
        
        private ArmandoShop.ProvidersClient.Model.Services.User userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Category> categories {
            get {
                return this.categoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.categoriesField, value) != true)) {
                    this.categoriesField = value;
                    this.RaisePropertyChanged("categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArmandoShop.ProvidersClient.Model.Services.User user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ArmandoShop.Model")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        private string passwordField;
        
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/ArmandoShop.Model")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.Dictionary<long, int> amountsField;
        
        private ArmandoShop.ProvidersClient.Model.Services.Customer customerField;
        
        private System.DateTime dateOfBuyField;
        
        private System.DateTime dateOfDeliverField;
        
        private bool deliveredField;
        
        private long idField;
        
        private System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Product> productsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<long, int> amounts {
            get {
                return this.amountsField;
            }
            set {
                if ((object.ReferenceEquals(this.amountsField, value) != true)) {
                    this.amountsField = value;
                    this.RaisePropertyChanged("amounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArmandoShop.ProvidersClient.Model.Services.Customer customer {
            get {
                return this.customerField;
            }
            set {
                if ((object.ReferenceEquals(this.customerField, value) != true)) {
                    this.customerField = value;
                    this.RaisePropertyChanged("customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dateOfBuy {
            get {
                return this.dateOfBuyField;
            }
            set {
                if ((this.dateOfBuyField.Equals(value) != true)) {
                    this.dateOfBuyField = value;
                    this.RaisePropertyChanged("dateOfBuy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dateOfDeliver {
            get {
                return this.dateOfDeliverField;
            }
            set {
                if ((this.dateOfDeliverField.Equals(value) != true)) {
                    this.dateOfDeliverField = value;
                    this.RaisePropertyChanged("dateOfDeliver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool delivered {
            get {
                return this.deliveredField;
            }
            set {
                if ((this.deliveredField.Equals(value) != true)) {
                    this.deliveredField = value;
                    this.RaisePropertyChanged("delivered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Product> products {
            get {
                return this.productsField;
            }
            set {
                if ((object.ReferenceEquals(this.productsField, value) != true)) {
                    this.productsField = value;
                    this.RaisePropertyChanged("products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/ArmandoShop.Model")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string addressField;
        
        private long idField;
        
        private string mailField;
        
        private string nameField;
        
        private string phoneField;
        
        private string surnameField;
        
        private ArmandoShop.ProvidersClient.Model.Services.User userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArmandoShop.ProvidersClient.Model.Services.User user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://schemas.datacontract.org/2004/07/ArmandoShop.Model")]
    [System.SerializableAttribute()]
    public partial class Contract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool chargedField;
        
        private System.DateTime dateField;
        
        private long idField;
        
        private ArmandoShop.ProvidersClient.Model.Services.Product productField;
        
        private ArmandoShop.ProvidersClient.Model.Services.Provider providerField;
        
        private int stockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool charged {
            get {
                return this.chargedField;
            }
            set {
                if ((this.chargedField.Equals(value) != true)) {
                    this.chargedField = value;
                    this.RaisePropertyChanged("charged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArmandoShop.ProvidersClient.Model.Services.Product product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArmandoShop.ProvidersClient.Model.Services.Provider provider {
            get {
                return this.providerField;
            }
            set {
                if ((object.ReferenceEquals(this.providerField, value) != true)) {
                    this.providerField = value;
                    this.RaisePropertyChanged("provider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ArmandoShop.ProvidersService", ConfigurationName="Model.Services.IProvidersService")]
    public interface IProvidersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ProvidersService/IProvidersService/GetProvider", ReplyAction="http://ArmandoShop.ProvidersService/IProvidersService/GetProviderResponse")]
        ArmandoShop.ProvidersClient.Model.Services.Provider GetProvider(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ProvidersService/IProvidersService/GetProviderByUser", ReplyAction="http://ArmandoShop.ProvidersService/IProvidersService/GetProviderByUserResponse")]
        ArmandoShop.ProvidersClient.Model.Services.Provider GetProviderByUser(ArmandoShop.ProvidersClient.Model.Services.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ProvidersService/IProvidersService/ListProviders", ReplyAction="http://ArmandoShop.ProvidersService/IProvidersService/ListProvidersResponse")]
        System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Provider> ListProviders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ProvidersService/IProvidersService/GetProvidersByCategory", ReplyAction="http://ArmandoShop.ProvidersService/IProvidersService/GetProvidersByCategoryRespo" +
            "nse")]
        System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Provider> GetProvidersByCategory(long idCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ProvidersService/IProvidersService/NewProvider", ReplyAction="http://ArmandoShop.ProvidersService/IProvidersService/NewProviderResponse")]
        long NewProvider(ArmandoShop.ProvidersClient.Model.Services.Provider provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ProvidersService/IProvidersService/ModifyProvider", ReplyAction="http://ArmandoShop.ProvidersService/IProvidersService/ModifyProviderResponse")]
        void ModifyProvider(ArmandoShop.ProvidersClient.Model.Services.Provider provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ProvidersService/IProvidersService/DeleteProvider", ReplyAction="http://ArmandoShop.ProvidersService/IProvidersService/DeleteProviderResponse")]
        void DeleteProvider(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProvidersServiceChannel : ArmandoShop.ProvidersClient.Model.Services.IProvidersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProvidersServiceClient : System.ServiceModel.ClientBase<ArmandoShop.ProvidersClient.Model.Services.IProvidersService>, ArmandoShop.ProvidersClient.Model.Services.IProvidersService {
        
        public ProvidersServiceClient() {
        }
        
        public ProvidersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProvidersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProvidersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProvidersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArmandoShop.ProvidersClient.Model.Services.Provider GetProvider(long id) {
            return base.Channel.GetProvider(id);
        }
        
        public ArmandoShop.ProvidersClient.Model.Services.Provider GetProviderByUser(ArmandoShop.ProvidersClient.Model.Services.User user) {
            return base.Channel.GetProviderByUser(user);
        }
        
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Provider> ListProviders() {
            return base.Channel.ListProviders();
        }
        
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Provider> GetProvidersByCategory(long idCategory) {
            return base.Channel.GetProvidersByCategory(idCategory);
        }
        
        public long NewProvider(ArmandoShop.ProvidersClient.Model.Services.Provider provider) {
            return base.Channel.NewProvider(provider);
        }
        
        public void ModifyProvider(ArmandoShop.ProvidersClient.Model.Services.Provider provider) {
            base.Channel.ModifyProvider(provider);
        }
        
        public void DeleteProvider(long id) {
            base.Channel.DeleteProvider(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ArmandoShop.categoryService", ConfigurationName="Model.Services.ICategoryService")]
    public interface ICategoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.categoryService/ICategoryService/ListCategories", ReplyAction="http://ArmandoShop.categoryService/ICategoryService/ListCategoriesResponse")]
        System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Category> ListCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.categoryService/ICategoryService/GetCategoriesByProvider", ReplyAction="http://ArmandoShop.categoryService/ICategoryService/GetCategoriesByProviderRespon" +
            "se")]
        System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Category> GetCategoriesByProvider(long idProvider);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.categoryService/ICategoryService/GetCategoriesNotInProvider", ReplyAction="http://ArmandoShop.categoryService/ICategoryService/GetCategoriesNotInProviderRes" +
            "ponse")]
        System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Category> GetCategoriesNotInProvider(long idProvider);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.categoryService/ICategoryService/AddProviderToCategory", ReplyAction="http://ArmandoShop.categoryService/ICategoryService/AddProviderToCategoryResponse" +
            "")]
        void AddProviderToCategory(long idProvider, long idCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.categoryService/ICategoryService/RemoveProviderOfCategory", ReplyAction="http://ArmandoShop.categoryService/ICategoryService/RemoveProviderOfCategoryRespo" +
            "nse")]
        void RemoveProviderOfCategory(long idProvider, long idCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.categoryService/ICategoryService/GetCategory", ReplyAction="http://ArmandoShop.categoryService/ICategoryService/GetCategoryResponse")]
        ArmandoShop.ProvidersClient.Model.Services.Category GetCategory(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.categoryService/ICategoryService/NewCategory", ReplyAction="http://ArmandoShop.categoryService/ICategoryService/NewCategoryResponse")]
        long NewCategory(ArmandoShop.ProvidersClient.Model.Services.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.categoryService/ICategoryService/DeleteCategory", ReplyAction="http://ArmandoShop.categoryService/ICategoryService/DeleteCategoryResponse")]
        void DeleteCategory(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.categoryService/ICategoryService/ModifyCategory", ReplyAction="http://ArmandoShop.categoryService/ICategoryService/ModifyCategoryResponse")]
        void ModifyCategory(ArmandoShop.ProvidersClient.Model.Services.Category category);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoryServiceChannel : ArmandoShop.ProvidersClient.Model.Services.ICategoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoryServiceClient : System.ServiceModel.ClientBase<ArmandoShop.ProvidersClient.Model.Services.ICategoryService>, ArmandoShop.ProvidersClient.Model.Services.ICategoryService {
        
        public CategoryServiceClient() {
        }
        
        public CategoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Category> ListCategories() {
            return base.Channel.ListCategories();
        }
        
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Category> GetCategoriesByProvider(long idProvider) {
            return base.Channel.GetCategoriesByProvider(idProvider);
        }
        
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Category> GetCategoriesNotInProvider(long idProvider) {
            return base.Channel.GetCategoriesNotInProvider(idProvider);
        }
        
        public void AddProviderToCategory(long idProvider, long idCategory) {
            base.Channel.AddProviderToCategory(idProvider, idCategory);
        }
        
        public void RemoveProviderOfCategory(long idProvider, long idCategory) {
            base.Channel.RemoveProviderOfCategory(idProvider, idCategory);
        }
        
        public ArmandoShop.ProvidersClient.Model.Services.Category GetCategory(long id) {
            return base.Channel.GetCategory(id);
        }
        
        public long NewCategory(ArmandoShop.ProvidersClient.Model.Services.Category category) {
            return base.Channel.NewCategory(category);
        }
        
        public void DeleteCategory(long id) {
            base.Channel.DeleteCategory(id);
        }
        
        public void ModifyCategory(ArmandoShop.ProvidersClient.Model.Services.Category category) {
            base.Channel.ModifyCategory(category);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ArmandoShop.ContractsService", ConfigurationName="Model.Services.IContractsService")]
    public interface IContractsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ContractsService/IContractsService/ListContracts", ReplyAction="http://ArmandoShop.ContractsService/IContractsService/ListContractsResponse")]
        System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Contract> ListContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ContractsService/IContractsService/NewContract", ReplyAction="http://ArmandoShop.ContractsService/IContractsService/NewContractResponse")]
        long NewContract(ArmandoShop.ProvidersClient.Model.Services.Contract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ContractsService/IContractsService/ModifyContract", ReplyAction="http://ArmandoShop.ContractsService/IContractsService/ModifyContractResponse")]
        void ModifyContract(ArmandoShop.ProvidersClient.Model.Services.Contract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ContractsService/IContractsService/DeleteContract", ReplyAction="http://ArmandoShop.ContractsService/IContractsService/DeleteContractResponse")]
        void DeleteContract(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContractsServiceChannel : ArmandoShop.ProvidersClient.Model.Services.IContractsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContractsServiceClient : System.ServiceModel.ClientBase<ArmandoShop.ProvidersClient.Model.Services.IContractsService>, ArmandoShop.ProvidersClient.Model.Services.IContractsService {
        
        public ContractsServiceClient() {
        }
        
        public ContractsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContractsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Contract> ListContracts() {
            return base.Channel.ListContracts();
        }
        
        public long NewContract(ArmandoShop.ProvidersClient.Model.Services.Contract contract) {
            return base.Channel.NewContract(contract);
        }
        
        public void ModifyContract(ArmandoShop.ProvidersClient.Model.Services.Contract contract) {
            base.Channel.ModifyContract(contract);
        }
        
        public void DeleteContract(long id) {
            base.Channel.DeleteContract(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ArmandoShop.ProductsService", ConfigurationName="Model.Services.IProductsService")]
    public interface IProductsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ProductsService/IProductsService/GetProduct", ReplyAction="http://ArmandoShop.ProductsService/IProductsService/GetProductResponse")]
        ArmandoShop.ProvidersClient.Model.Services.Product GetProduct(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ProductsService/IProductsService/ListProducts", ReplyAction="http://ArmandoShop.ProductsService/IProductsService/ListProductsResponse")]
        System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Product> ListProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ProductsService/IProductsService/GetProductsByCategory", ReplyAction="http://ArmandoShop.ProductsService/IProductsService/GetProductsByCategoryResponse" +
            "")]
        System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Product> GetProductsByCategory(long idCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ProductsService/IProductsService/NewProduct", ReplyAction="http://ArmandoShop.ProductsService/IProductsService/NewProductResponse")]
        long NewProduct(ArmandoShop.ProvidersClient.Model.Services.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ProductsService/IProductsService/ModifyProduct", ReplyAction="http://ArmandoShop.ProductsService/IProductsService/ModifyProductResponse")]
        void ModifyProduct(ArmandoShop.ProvidersClient.Model.Services.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.ProductsService/IProductsService/DeleteProduct", ReplyAction="http://ArmandoShop.ProductsService/IProductsService/DeleteProductResponse")]
        void DeleteProduct(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductsServiceChannel : ArmandoShop.ProvidersClient.Model.Services.IProductsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductsServiceClient : System.ServiceModel.ClientBase<ArmandoShop.ProvidersClient.Model.Services.IProductsService>, ArmandoShop.ProvidersClient.Model.Services.IProductsService {
        
        public ProductsServiceClient() {
        }
        
        public ProductsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArmandoShop.ProvidersClient.Model.Services.Product GetProduct(long id) {
            return base.Channel.GetProduct(id);
        }
        
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Product> ListProducts() {
            return base.Channel.ListProducts();
        }
        
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Product> GetProductsByCategory(long idCategory) {
            return base.Channel.GetProductsByCategory(idCategory);
        }
        
        public long NewProduct(ArmandoShop.ProvidersClient.Model.Services.Product product) {
            return base.Channel.NewProduct(product);
        }
        
        public void ModifyProduct(ArmandoShop.ProvidersClient.Model.Services.Product product) {
            base.Channel.ModifyProduct(product);
        }
        
        public void DeleteProduct(long id) {
            base.Channel.DeleteProduct(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ArmandoShop.OrdersService", ConfigurationName="Model.Services.IOrdersService")]
    public interface IOrdersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.OrdersService/IOrdersService/ListOrders", ReplyAction="http://ArmandoShop.OrdersService/IOrdersService/ListOrdersResponse")]
        System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Order> ListOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.OrdersService/IOrdersService/GetOrder", ReplyAction="http://ArmandoShop.OrdersService/IOrdersService/GetOrderResponse")]
        ArmandoShop.ProvidersClient.Model.Services.Order GetOrder(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.OrdersService/IOrdersService/NewOrder", ReplyAction="http://ArmandoShop.OrdersService/IOrdersService/NewOrderResponse")]
        long NewOrder(ArmandoShop.ProvidersClient.Model.Services.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.OrdersService/IOrdersService/ModifyOrder", ReplyAction="http://ArmandoShop.OrdersService/IOrdersService/ModifyOrderResponse")]
        void ModifyOrder(ArmandoShop.ProvidersClient.Model.Services.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.OrdersService/IOrdersService/DeleteOrder", ReplyAction="http://ArmandoShop.OrdersService/IOrdersService/DeleteOrderResponse")]
        void DeleteOrder(long ikd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdersServiceChannel : ArmandoShop.ProvidersClient.Model.Services.IOrdersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersServiceClient : System.ServiceModel.ClientBase<ArmandoShop.ProvidersClient.Model.Services.IOrdersService>, ArmandoShop.ProvidersClient.Model.Services.IOrdersService {
        
        public OrdersServiceClient() {
        }
        
        public OrdersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Order> ListOrders() {
            return base.Channel.ListOrders();
        }
        
        public ArmandoShop.ProvidersClient.Model.Services.Order GetOrder(long id) {
            return base.Channel.GetOrder(id);
        }
        
        public long NewOrder(ArmandoShop.ProvidersClient.Model.Services.Order order) {
            return base.Channel.NewOrder(order);
        }
        
        public void ModifyOrder(ArmandoShop.ProvidersClient.Model.Services.Order order) {
            base.Channel.ModifyOrder(order);
        }
        
        public void DeleteOrder(long ikd) {
            base.Channel.DeleteOrder(ikd);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ArmandoShop.CustomersService", ConfigurationName="Model.Services.ICustomersService")]
    public interface ICustomersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.CustomersService/ICustomersService/GetCustomer", ReplyAction="http://ArmandoShop.CustomersService/ICustomersService/GetCustomerResponse")]
        ArmandoShop.ProvidersClient.Model.Services.Customer GetCustomer(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.CustomersService/ICustomersService/GetCustomerByUser", ReplyAction="http://ArmandoShop.CustomersService/ICustomersService/GetCustomerByUserResponse")]
        ArmandoShop.ProvidersClient.Model.Services.Customer GetCustomerByUser(ArmandoShop.ProvidersClient.Model.Services.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.CustomersService/ICustomersService/ListCustomers", ReplyAction="http://ArmandoShop.CustomersService/ICustomersService/ListCustomersResponse")]
        System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Customer> ListCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.CustomersService/ICustomersService/NewCustomer", ReplyAction="http://ArmandoShop.CustomersService/ICustomersService/NewCustomerResponse")]
        long NewCustomer(ArmandoShop.ProvidersClient.Model.Services.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.CustomersService/ICustomersService/ModifyCustomer", ReplyAction="http://ArmandoShop.CustomersService/ICustomersService/ModifyCustomerResponse")]
        void ModifyCustomer(ArmandoShop.ProvidersClient.Model.Services.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.CustomersService/ICustomersService/DeleteCustomer", ReplyAction="http://ArmandoShop.CustomersService/ICustomersService/DeleteCustomerResponse")]
        void DeleteCustomer(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomersServiceChannel : ArmandoShop.ProvidersClient.Model.Services.ICustomersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomersServiceClient : System.ServiceModel.ClientBase<ArmandoShop.ProvidersClient.Model.Services.ICustomersService>, ArmandoShop.ProvidersClient.Model.Services.ICustomersService {
        
        public CustomersServiceClient() {
        }
        
        public CustomersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArmandoShop.ProvidersClient.Model.Services.Customer GetCustomer(long id) {
            return base.Channel.GetCustomer(id);
        }
        
        public ArmandoShop.ProvidersClient.Model.Services.Customer GetCustomerByUser(ArmandoShop.ProvidersClient.Model.Services.User user) {
            return base.Channel.GetCustomerByUser(user);
        }
        
        public System.Collections.Generic.List<ArmandoShop.ProvidersClient.Model.Services.Customer> ListCustomers() {
            return base.Channel.ListCustomers();
        }
        
        public long NewCustomer(ArmandoShop.ProvidersClient.Model.Services.Customer customer) {
            return base.Channel.NewCustomer(customer);
        }
        
        public void ModifyCustomer(ArmandoShop.ProvidersClient.Model.Services.Customer customer) {
            base.Channel.ModifyCustomer(customer);
        }
        
        public void DeleteCustomer(long id) {
            base.Channel.DeleteCustomer(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ArmandoShop.UsersService", ConfigurationName="Model.Services.IUsersService")]
    public interface IUsersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.UsersService/IUsersService/Login", ReplyAction="http://ArmandoShop.UsersService/IUsersService/LoginResponse")]
        ArmandoShop.ProvidersClient.Model.Services.User Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.UsersService/IUsersService/IsUsernameAvaiable", ReplyAction="http://ArmandoShop.UsersService/IUsersService/IsUsernameAvaiableResponse")]
        bool IsUsernameAvaiable(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.UsersService/IUsersService/NewUser", ReplyAction="http://ArmandoShop.UsersService/IUsersService/NewUserResponse")]
        long NewUser(ArmandoShop.ProvidersClient.Model.Services.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.UsersService/IUsersService/ModifyUser", ReplyAction="http://ArmandoShop.UsersService/IUsersService/ModifyUserResponse")]
        void ModifyUser(ArmandoShop.ProvidersClient.Model.Services.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArmandoShop.UsersService/IUsersService/DeleteUser", ReplyAction="http://ArmandoShop.UsersService/IUsersService/DeleteUserResponse")]
        void DeleteUser(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersServiceChannel : ArmandoShop.ProvidersClient.Model.Services.IUsersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersServiceClient : System.ServiceModel.ClientBase<ArmandoShop.ProvidersClient.Model.Services.IUsersService>, ArmandoShop.ProvidersClient.Model.Services.IUsersService {
        
        public UsersServiceClient() {
        }
        
        public UsersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArmandoShop.ProvidersClient.Model.Services.User Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public bool IsUsernameAvaiable(string username) {
            return base.Channel.IsUsernameAvaiable(username);
        }
        
        public long NewUser(ArmandoShop.ProvidersClient.Model.Services.User user) {
            return base.Channel.NewUser(user);
        }
        
        public void ModifyUser(ArmandoShop.ProvidersClient.Model.Services.User user) {
            base.Channel.ModifyUser(user);
        }
        
        public void DeleteUser(long id) {
            base.Channel.DeleteUser(id);
        }
    }
}
